/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gsabsence.UI;

import gsabsence.entities.Absence;
import gsabsence.service.AbsenceService;
import java.awt.BorderLayout;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author badrBouaichi
 */
public class ChartsAbsenceEmploye extends javax.swing.JInternalFrame {

    /**
     * Creates new form Charts1
     */
    public ChartsAbsenceEmploye() {
        initComponents();
        setFrameIcon(
                    new ImageIcon(getClass().getResource("/images/GsAbsence-icon.png"))
        );
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        loadChart();
    }

    private void loadChart() {

        AbsenceService absenceService = new AbsenceService();
        List<Absence> absences = absenceService.findAll();

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        // key = employe name, value = count
        Map<String, Integer> countMap = new HashMap<>();

        for (Absence a : absences) {
            String empName = a.getEmploye().getNom();

            countMap.put(empName, countMap.getOrDefault(empName, 0) + 1);
        }

        // fill dataset
        for (Map.Entry<String, Integer> entry : countMap.entrySet()) {
            dataset.addValue(entry.getValue(), "Absences", entry.getKey());
        }

        JFreeChart chart = ChartFactory.createBarChart(
                    "Nombre d'absences par employé",
                    "Employé",
                    "Nombre d'absences",
                    dataset
        );

        ChartPanel chartPanel = new ChartPanel(chart);

        chartsPanel.removeAll();
        chartsPanel.setLayout(new BorderLayout());
        chartsPanel.add(chartPanel, BorderLayout.CENTER);
        chartsPanel.revalidate();
        chartsPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartsPanel = new javax.swing.JPanel();

        setTitle("Gestion Absence");

        javax.swing.GroupLayout chartsPanelLayout = new javax.swing.GroupLayout(chartsPanel);
        chartsPanel.setLayout(chartsPanelLayout);
        chartsPanelLayout.setHorizontalGroup(
            chartsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        chartsPanelLayout.setVerticalGroup(
            chartsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chartsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartsPanel;
    // End of variables declaration//GEN-END:variables
}
