/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gsabsence.UI;

import gsabsence.entities.Absence;
import gsabsence.service.AbsenceService;
import java.awt.BorderLayout;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author badrBouaichi
 */
public class ChartsAbsenceParType extends javax.swing.JInternalFrame {

    /**
     * Creates new form ChartsAbsenceParType
     */
    public ChartsAbsenceParType() {
        initComponents();
        setFrameIcon(
                    new ImageIcon(getClass().getResource("/images/GsAbsence-icon.png"))
        );
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        loadChart();
    }

    private void loadChart() {

        AbsenceService service = new AbsenceService();
        List<Absence> absences = service.findAll();

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        // Compter les absences par type
        Map<String, Integer> counter = new HashMap<>();

        for (Absence a : absences) {
            String typeName = a.getTypeAbsemce().getLibelle();
            counter.put(typeName, counter.getOrDefault(typeName, 0) + 1);
        }

        // Remplir le dataset
        for (Map.Entry<String, Integer> entry : counter.entrySet()) {
            dataset.addValue(entry.getValue(), "Absences", entry.getKey());
        }

        JFreeChart chart = ChartFactory.createBarChart(
                    "Nombre d'absences par type",
                    "Type d'absence",
                    "Nombre",
                    dataset
        );

        ChartPanel chartPanel = new ChartPanel(chart);

        chartsPanel.removeAll();
        chartsPanel.setLayout(new BorderLayout());
        chartsPanel.add(chartPanel, BorderLayout.CENTER);
        chartsPanel.revalidate();
        chartsPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartsPanel = new javax.swing.JPanel();

        chartsPanel.setToolTipText("");

        javax.swing.GroupLayout chartsPanelLayout = new javax.swing.GroupLayout(chartsPanel);
        chartsPanel.setLayout(chartsPanelLayout);
        chartsPanelLayout.setHorizontalGroup(
            chartsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );
        chartsPanelLayout.setVerticalGroup(
            chartsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chartsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartsPanel;
    // End of variables declaration//GEN-END:variables
}
