/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gsabsence.UI;

import gsabsence.service.EmployeService;
import java.sql.Connection;
import gsabsence.entities.Employe;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author badrBouaichi
 */
public class EmployeUI extends javax.swing.JInternalFrame {

    private EmployeService employeSrvice;
    private static Connection connection = null;
    private DefaultTableModel model = null;
    private int currentEmplyeId = 0;

    /**
     * Creates new form Employe
     */
    public EmployeUI() {
        initComponents();
        setFrameIcon(
                    new ImageIcon(getClass().getResource("/images/GsAbsence-icon.png"))
        );
        employeSrvice = new EmployeService();
        model = (DefaultTableModel) jTableEmploye.getModel();

        jTableEmploye.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                seletedEmpley();
            }
        });
        loadEmployes();

    }

    public void clearForm() {
        currentEmplyeId = 0;
        departemantTxt.setText("");
        posteTxt.setText("");
        nomTxt.setText("");
    }

    public void loadEmployes() {
        model.setRowCount(0);
        for (Employe e : employeSrvice.findAll()) {
            model.addRow(new Object[]{
                e.getId(),
                e.getNom(),
                e.getDepartement(),
                e.getPost()
            });
        }
    }

    public void seletedEmpley() {
        int selectedRow = jTableEmploye.getSelectedRow();

        // Vérifier qu'une ligne est sélectionnée
        if (selectedRow == -1) {

            return;
        }

        // Récupérer l'ID (1ère colonne = index 0)
        int idEmploye = Integer.parseInt(
                    jTableEmploye.getValueAt(selectedRow, 0).toString()
        );

        // Récupérer l'employé depuis la BD
        EmployeService es = new EmployeService();
        Employe employe = es.findById(idEmploye);

        if (employe != null) {
            System.out.println("Employé sélectionné : " + employe.getNom());

            currentEmplyeId = employe.getId();
            nomTxt.setText(employe.getNom());
            departemantTxt.setText(employe.getDepartement());
            posteTxt.setText(employe.getPost());
        } else {
            currentEmplyeId = 0;
            JOptionPane.showMessageDialog(this,
                        "Employé introuvable",
                        "Erreur",
                        JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formEmploye = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomTxt = new javax.swing.JTextField();
        departemantTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        posteTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ajouterBtn = new javax.swing.JButton();
        ajouterBtn1 = new javax.swing.JButton();
        ajouterBtn2 = new javax.swing.JButton();
        viderBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmploye = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setResizable(true);
        setTitle("Gestion emplye");
        setToolTipText("");
        setAutoscrolls(true);

        formEmploye.setToolTipText("Ajoiuter employe");

        jLabel1.setText("Nom");

        nomTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomTxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Departemant");

        jLabel3.setText("Poste");

        javax.swing.GroupLayout formEmployeLayout = new javax.swing.GroupLayout(formEmploye);
        formEmploye.setLayout(formEmployeLayout);
        formEmployeLayout.setHorizontalGroup(
            formEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formEmployeLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(formEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formEmployeLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(posteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formEmployeLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(departemantTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formEmployeLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(nomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        formEmployeLayout.setVerticalGroup(
            formEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formEmployeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(formEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departemantTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ajouterBtn.setText("Ajouter");
        ajouterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterBtnActionPerformed(evt);
            }
        });

        ajouterBtn1.setText("Modifier");
        ajouterBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterBtn1ActionPerformed(evt);
            }
        });

        ajouterBtn2.setText("Supprimer");
        ajouterBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterBtn2ActionPerformed(evt);
            }
        });

        viderBtn.setText("Vider");
        viderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ajouterBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ajouterBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ajouterBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(ajouterBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ajouterBtn1)
                .addGap(18, 18, 18)
                .addComponent(ajouterBtn2)
                .addGap(18, 18, 18)
                .addComponent(viderBtn)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTableEmploye.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Departemant", "Post", "Nombre absence"
            }
        ));
        jScrollPane1.setViewportView(jTableEmploye);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formEmploye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomTxtActionPerformed

    private void viderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viderBtnActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_viderBtnActionPerformed

    private void ajouterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterBtnActionPerformed
        // TODO add your handling code here:
        Employe e = new Employe(nomTxt.getText(), departemantTxt.getText(), posteTxt.getText());
        boolean isAdded = false;
        isAdded = employeSrvice.create(e);
        if (isAdded) {
            JOptionPane.showMessageDialog(
                        this,
                        "Employe " + e.getNom() + " bien ajouter",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
            );
            clearForm();
            loadEmployes();
        } else {
            JOptionPane.showMessageDialog(
                        this,
                        "Erreur ajoute de " + e.getNom(),
                        "Erreur",
                        JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_ajouterBtnActionPerformed

    private void ajouterBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterBtn1ActionPerformed
        // TODO add your handling code here:
        if (currentEmplyeId > 0) {
            Employe e = new Employe(currentEmplyeId, nomTxt.getText(), departemantTxt.getText(), posteTxt.getText());
            boolean isUpdated = false;
            isUpdated = employeSrvice.update(e);
            if (isUpdated) {
                JOptionPane.showMessageDialog(
                            this,
                            "Employe " + e.getNom() + " bien modifier",
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE
                );
                clearForm();
                loadEmployes();
            } else {
                JOptionPane.showMessageDialog(
                            this,
                            "Erreur modification de " + e.getNom(),
                            "Erreur",
                            JOptionPane.ERROR_MESSAGE
                );
            }
        } else {
            JOptionPane.showMessageDialog(
                        this,
                        "Erreur auccun employer a ete selectionner ",
                        "Erreur",
                        JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_ajouterBtn1ActionPerformed

    private void ajouterBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterBtn2ActionPerformed
        // TODO add your handling code here:
        if (currentEmplyeId > 0) {
            Employe e = new Employe(currentEmplyeId, nomTxt.getText(), departemantTxt.getText(), posteTxt.getText());
            boolean isDeleted = false;
            isDeleted = employeSrvice.delete(e);
            if (isDeleted) {
                JOptionPane.showMessageDialog(
                            this,
                            "Employe " + e.getNom() + " bien supprimer",
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE
                );
                clearForm();
                loadEmployes();
            } else {
                JOptionPane.showMessageDialog(
                            this,
                            "Erreur supression de " + e.getNom(),
                            "Erreur",
                            JOptionPane.ERROR_MESSAGE
                );
            }
        } else {
            JOptionPane.showMessageDialog(
                        this,
                        "Erreur auccun employer a ete selectionner ",
                        "Erreur",
                        JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_ajouterBtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterBtn;
    private javax.swing.JButton ajouterBtn1;
    private javax.swing.JButton ajouterBtn2;
    private javax.swing.JTextField departemantTxt;
    private javax.swing.JPanel formEmploye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmploye;
    private javax.swing.JTextField nomTxt;
    private javax.swing.JTextField posteTxt;
    private javax.swing.JButton viderBtn;
    // End of variables declaration//GEN-END:variables
}
