/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gsabsence;

import gsabsence.connexion.Connexion;
import gsabsence.entities.User;
import gsabsence.service.userService;
import gsabsence.util.UiUtils;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author badrBouaichi
 */
public class Registre extends javax.swing.JFrame {

    private userService user;
    private static Connection connection = null;

    /**
     * Creates new form Registre
     */
    public Registre() {
        initComponents();
        UiUtils.setAppIcon(this);
        reconnectBtn.setVisible(false);
        try {
            connection = Connexion.getConnection();
            if (connection == null) {
                JOptionPane.showMessageDialog(
                            this,
                            "Please check connexion",
                            "Connexion Error",
                            JOptionPane.WARNING_MESSAGE
                );
                inscrireBtn.setVisible(false);
                reconnectBtn.setVisible(true);
            }
            user = new userService();
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inscrireBtn = new javax.swing.JButton();
        userNameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mdpTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmdpTxt = new javax.swing.JTextField();
        reconnectBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inscrire");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setText("Username");

        inscrireBtn.setText("Inscrire");
        inscrireBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscrireBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Email");

        jLabel3.setText("Mot de passe");

        jLabel4.setText("Confirmer Mot de passe");

        reconnectBtn.setText("Reconnect");
        reconnectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reconnectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inscrireBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reconnectBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(userNameTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmdpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mdpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mdpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inscrireBtn)
                    .addComponent(reconnectBtn))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inscrireBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscrireBtnActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String userName = userNameTxt.getText();
        String email = emailTxt.getText();
        String passeword = mdpTxt.getText();
        String confirmPasseword = cmdpTxt.getText();
        if (userName.isEmpty() || passeword.isEmpty() || email.isEmpty() || confirmPasseword.isEmpty()) {
            JOptionPane.showMessageDialog(
                        this,
                        "Please enter username and email and password",
                        "Validation Error",
                        JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        if (!passeword.equals(confirmPasseword)) {
            JOptionPane.showMessageDialog(
                        this,
                        "Please password and confirme passeword et different",
                        "Validation Error",
                        JOptionPane.WARNING_MESSAGE
            );
            System.out.println("✅ passeword :" + passeword);
            System.out.println("✅ confirmPasseword :" + confirmPasseword);
            return;
        }
        boolean isRegistre = false;
        boolean isExist = false;

        isExist = user.emailExists(email);
        if (isExist) {
            JOptionPane.showMessageDialog(
                        this,
                        "Erreur email deja exit",
                        "Erreur address mail",
                        JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        isRegistre = user.register(userName, email, passeword);
        if (isRegistre) {
            JOptionPane.showMessageDialog(
                        this,
                        "Utilusateur bien cree",
                        "Creation utilusateur",
                        JOptionPane.INFORMATION_MESSAGE
            );
            new Login().setVisible(isRegistre);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(
                        this,
                        "Erreur leur de creation compte essayer apres quelque minutes svp",
                        "Erreur Inscription",
                        JOptionPane.WARNING_MESSAGE
            );
        }

    }//GEN-LAST:event_inscrireBtnActionPerformed

    private void reconnectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reconnectBtnActionPerformed
        // TODO add your handling code here:
        try {
            connection = Connexion.getConnection();
            if (connection == null) {
                JOptionPane.showMessageDialog(
                            this,
                            "Please check connexion",
                            "Connexion Error",
                            JOptionPane.WARNING_MESSAGE
                );
                inscrireBtn.setVisible(false);
                reconnectBtn.setVisible(true);
            } else {
                inscrireBtn.setVisible(true);
                reconnectBtn.setVisible(false);
            }
            user = new userService();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_reconnectBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cmdpTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JButton inscrireBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField mdpTxt;
    private javax.swing.JButton reconnectBtn;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
